from turtle import *
bgcolor("black")
pencolor('white')
fillcolor('red')
pensize(5)
def heart(f,c)
    begin_fill()
    lt(40)
    fd(f)
    circle(c, 210)
    rt(138)
    circle(c, 210)
    hideturtle()
done()